DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255), GENRE_ID BIGINT);
DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOKS_AUTHORS(BOOK_ID BIGINT, AUTHOR_ID BIGINT);

