spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    #initialization-mode: always
    #schema: schema.sql
    #data: data.sql
    sql-script-encoding: UTF-8
    platform: h2
  sql:
    init:
      mode: always
      data-locations: data-h2.sql
      schema-locations: schema-h2.sql
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false


  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost

#mongock:
#  #runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
#  change-logs-scan-package:
#    - ru.otus.spring.mongock




batchsize: 5
crushJob: true
