DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), PRICE INT, DRAWINGS VARCHAR(255), DECORATION VARCHAR(255), REVIEW VARCHAR(255), ISBN
VARCHAR(255), PAGECOUNT INT);

DROP TABLE IF EXISTS PICTURES;
CREATE TABLE PICTURES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), PRICE INT,  FRAMEMATERIAL VARCHAR(255));

DROP SEQUENCE IF EXISTS BOOKS_SEQ;
CREATE SEQUENCE BOOKS_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS PICTURES_SEQ;
CREATE SEQUENCE PICTURES_SEQ START WITH 1 INCREMENT BY 1;
