spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    #initialization-mode: always
    #schema: schema.sql
    #data: data.sql
    driver-class-name: org.postgresql.Driver
    password: sa
    username: sa
  sql:
    init:
      mode: always
      #data-locations: data.sql
      #schema-locations: schema.sql
      encoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
  data:
    rest:
      basePath: /api

StephenKing:
  minpagerate: 30
  maxpagerate: 50
  picturechance: 10
  bookpagecount: 350
  minprice: 100
  maxprice: 1000
  healthcheckthreshold: 10000 # 10 seconds


management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always

# Его же используем в logback.xml
#logging:
#  file:
#    path: ./spring-16-homework/logs/
#    name: ./spring-16-homework/logs/SpringIntegration.log
